name: ptouch-print # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: cli to print labels on Brother P-Touch
description: |
  ptouch-print is a command line tool to print labels on Brother P-Touch
  printers on Linux.
  .  
  Supported printers (some might have quirks)
  PT-2420PC
  PT-2450PC
  PT-1950
  PT-2700
  PT-1230PC
  PT-2430PC
  PT-2730
  PT-H500
  PT-E500
  PT-P700
  PT-P750W
  PT-D410
  PT-D450
  PT-D460BT
  PT-D600
  PT-D610BT
  PT-P710BT

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
website: https://git.familie-radermacher.ch/linux/ptouch-print.git/tree/

apps:
  ptouch-print:
    command: /usr/bin/ptouch-print
    plugs: 
      - raw-usb
      - network-control

parts:
  ptouch-print:
    plugin: cmake
    source-type: git
    source: https://git.familie-radermacher.ch/linux/ptouch-print.git

    build-packages:
      - libgd-dev
      - libusb-1.0-0-dev
      - gettext
    stage-packages:
      - libgd3
      - libusb-1.0-0
